name: Build and Deploy cvab-app to AWS S3 Production
on:
  workflow_dispatch:
    branches: [ production ]

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: cvandrewsbible.com
      DIST: build
      AWS_REGION: us-east-1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
          role-to-assume: arn:aws:iam::659747462473:role/Cvab-GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # Hello from AWS: WhoAmI
    - name: Sts GetCallerIdentity
      run: |
        aws sts get-caller-identity
        
    - name: Install Dependencies
      run: |
        node --version
        yarn install --prod

    - name: Build cvab-app
      run: yarn build

    - name: Copy files to Production with the AWS CLI
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}